// Occupation name mapping (IPUMS OCC codes)
const occupationNames = {
  10: "Chief Executives And Legislators",
  20: "General And Operations Managers",
  40: "Advertising And Promotions Managers",
  51: "Marketing Managers",
  52: "Sales Managers",
  60: "Public Relations And Fundraising Managers",
  101: "Administrative Services Managers",
  102: "Facilities Managers",
  110: "Computer And Information Systems Managers",
  120: "Financial Managers",
  135: "Compensation And Benefits Managers",
  136: "Human Resources Managers",
  137: "Training And Development Managers",
  140: "Industrial Production Managers",
  150: "Purchasing Managers",
  160: "Transportation, Storage, And Distribution Managers",
  205: "Farmers, Ranchers, And Other Agricultural Managers",
  220: "Construction Managers",
  230: "Education And Childcare Administrators",
  300: "Architectural And Engineering Managers",
  310: "Food Service Managers",
  335: "Entertainment and Recreation Managers",
  340: "Lodging Managers",
  350: "Medical And Health Services Managers",
  360: "Natural Sciences Managers",
  410: "Property, Real Estate, And Community Association Managers",
  420: "Social And Community Service Managers",
  425: "Emergency Management Directors",
  440: "Other Managers",
  500: "Agents And Business Managers Of Artists, Performers, And Athletes",
  510: "Buyers And Purchasing Agents, Farm Products",
  520: "Wholesale And Retail Buyers, Except Farm Products",
  530: "Purchasing Agents, Except Wholesale, Retail, And Farm Products",
  540: "Claims Adjusters, Appraisers, Examiners, And Investigators",
  565: "Compliance Officers",
  600: "Cost Estimators",
  630: "Human Resources Workers",
  640: "Compensation, Benefits, And Job Analysis Specialists",
  650: "Training And Development Specialists",
  700: "Logisticians",
  705: "Project Management Specialists",
  710: "Management Analysts",
  725: "Meeting, Convention, And Event Planners",
  726: "Fundraisers",
  735: "Market Research Analysts And Marketing Specialists",
  750: "Business Operations Specialists, All Other",
  800: "Accountants And Auditors",
  810: "Property Appraisers and Assessors",
  820: "Budget Analysts",
  830: "Credit Analysts",
  845: "Financial And Investment Analysts",
  850: "Personal Financial Advisors",
  860: "Insurance Underwriters",
  900: "Financial Examiners",
  910: "Credit Counselors And Loan Officers",
  930: "Tax Examiners And Collectors, And Revenue Agents",
  940: "Tax Preparers",
  960: "Other Financial Specialists",
  1005: "Computer And Information Research Scientists",
  1006: "Computer Systems Analysts",
  1007: "Information Security Analysts",
  1010: "Computer Programmers",
  1021: "Software Developers",
  1022: "Software Quality Assurance Analysts and Testers",
  1031: "Web Developers",
  1032: "Web And Digital Interface Designers",
  1050: "Computer Support Specialists",
  1065: "Database Administrators and Architects",
  1105: "Network And Computer Systems Administrators",
  1106: "Computer Network Architects",
  1108: "Computer Occupations, All Other",
  1200: "Actuaries",
  1220: "Operations Research Analysts",
  1240: "Other Mathematical Science Occupations",
  1305: "Architects, Except Landscape And Naval",
  1306: "Landscape Architects",
  1310: "Surveyors, Cartographers, And Photogrammetrists",
  1320: "Aerospace Engineers",
  1340: "Biomedical And Agricultural Engineers",
  1350: "Chemical Engineers",
  1360: "Civil Engineers",
  1400: "Computer Hardware Engineers",
  1410: "Electrical And Electronics Engineers",
  1420: "Environmental Engineers",
  1430: "Industrial Engineers, Including Health And Safety",
  1440: "Marine Engineers And Naval Architects",
  1450: "Materials Engineers",
  1460: "Mechanical Engineers",
  1520: "Petroleum, Mining And Geological Engineers",
  1530: "Other Engineers",
  1541: "Architectural And Civil Drafters",
  1545: "Other Drafters",
  1551: "Electrical And Electronic Engineering Technologists",
  1555: "Other Engineering Technologists And Technicians",
  1560: "Surveying And Mapping Technicians",
  1600: "Agricultural And Food Scientists",
  1610: "Biological Scientists",
  1640: "Conservation Scientists And Foresters",
  1650: "Other Life Scientists",
  1700: "Astronomers And Physicists",
  1710: "Atmospheric And Space Scientists",
  1720: "Chemists And Materials Scientists",
  1745: "Environmental Scientists And Specialists",
  1750: "Geoscientists And Hydrologists",
  1760: "Physical Scientists, All Other",
  1800: "Economists",
  1821: "Clinical And Counseling Psychologists",
  1822: "School Psychologists",
  1825: "Other Psychologists",
  1840: "Urban And Regional Planners",
  1860: "Other Social Scientists",
  1900: "Agricultural And Food Science Technicians",
  1910: "Biological Technicians",
  1920: "Chemical Technicians",
  1935: "Environmental Science and Geoscience Technicians",
  1970: "Other Life, Physical, And Social Science Technicians",
  1980: "Occupational Health And Safety Specialists",
  2001: "Substance Abuse And Behavioral Disorder Counselors",
  2002: "Educational, Guidance, And Career Counselors",
  2003: "Marriage And Family Therapists",
  2004: "Mental Health Counselors",
  2005: "Rehabilitation Counselors",
  2006: "Counselors, All Other",
  2011: "Child, Family, And School Social Workers",
  2012: "Healthcare Social Workers",
  2013: "Mental Health And Substance Abuse Social Workers",
  2014: "Social Workers, All Other",
  2015: "Probation Officers And Correctional Treatment Specialists",
  2016: "Social And Human Service Assistants",
  2025: "Other Community and Social Service Specialists",
  2040: "Clergy",
  2050: "Directors, Religious Activities And Education",
  2060: "Religious Workers, All Other",
  2100: "Lawyers, And Judges, Magistrates",
  2105: "Judicial Law Clerks",
  2145: "Paralegals And Legal Assistants",
  2170: "Title Examiners, Abstractors, and Searchers",
  2180: "Legal Support Workers, All Other",
  2205: "Postsecondary Teachers",
  2300: "Preschool And Kindergarten Teachers",
  2310: "Elementary And Middle School Teachers",
  2320: "Secondary School Teachers",
  2330: "Special Education Teachers",
  2350: "Tutors",
  2360: "Other Teachers and Instructors",
  2400: "Archivists, Curators, And Museum Technicians",
  2435: "Librarians And Media Collections Specialists",
  2440: "Library Technicians",
  2545: "Teaching Assistants",
  2555: "Other Educational Instruction and Library Workers",
  2600: "Artists And Related Workers",
  2631: "Commercial And Industrial Designers",
  2632: "Fashion Designers",
  2633: "Floral Designers",
  2634: "Graphic Designers",
  2635: "Interior Designers",
  2636: "Merchandise Displayers And Window Trimmers",
  2640: "Other Designers",
  2700: "Actors",
  2710: "Producers And Directors",
  2721: "Athletes and Sports Competitors",
  2722: "Coaches and Scouts",
  2723: "Umpires, Referees, And Other Sports Officials",
  2740: "Dancers And Choreographers",
  2751: "Music Directors and Composers",
  2752: "Musicians and Singers",
  2755: "Disc Jockeys, Except Radio",
  2770: "Entertainers And Performers, Sports and Related Workers",
  2805: "Broadcast Announcers And Radio Disc Jockeys",
  2810: "News Analysts, Reporters, And Journalists",
  2825: "Public Relations Specialists",
  2830: "Editors",
  2840: "Technical Writers",
  2850: "Writers And Authors",
  2861: "Interpreters and Translators",
  2862: "Court Reporters and Simultaneous Captioners",
  2865: "Media And Communication Workers, All Other",
  2905: "Other Media And Communication Equipment Workers",
  2910: "Photographers",
  2920: "Television, Video, And Film Camera Operators",
  3000: "Chiropractors",
  3010: "Dentists",
  3030: "Dietitians And Nutritionists",
  3040: "Optometrists",
  3050: "Pharmacists",
  3090: "Physicians",
  3100: "Surgeons",
  3110: "Physician Assistants",
  3120: "Podiatrists",
  3140: "Audiologists",
  3150: "Occupational Therapists",
  3160: "Physical Therapists",
  3200: "Radiation Therapists",
  3210: "Recreational Therapists",
  3220: "Respiratory Therapists",
  3230: "Speech-Language Pathologists",
  3245: "Other Therapists",
  3250: "Veterinarians",
  3255: "Registered Nurses",
  3256: "Nurse Anesthetists",
  3258: "Nurse Practitioners, And Nurse Midwives",
  3261: "Acupuncturists",
  3270: "Healthcare Diagnosing Or Treating Practitioners",
  3300: "Clinical Laboratory Technologists And Technicians",
  3310: "Dental Hygienists",
  3321: "Cardiovascular Technologists and Technicians",
  3322: "Diagnostic Medical Sonographers",
  3323: "Radiologic Technologists And Technicians",
  3324: "Magnetic Resonance Imaging Technologists",
  3330: "Nuclear Medicine Technologists and Medical Dosimetrists",
  3401: "Emergency Medical Technicians",
  3402: "Paramedics",
  3421: "Pharmacy Technicians",
  3422: "Psychiatric Technicians",
  3423: "Surgical Technologists",
  3424: "Veterinary Technologists and Technicians",
  3430: "Dietetic Technicians And Ophthalmic Medical Technicians",
  3500: "Licensed Practical And Licensed Vocational Nurses",
  3515: "Medical Records Specialists",
  3520: "Opticians, Dispensing",
  3545: "Miscellaneous Health Technologists and Technicians",
  3550: "Other Healthcare Practitioners",
  3601: "Home Health Aides",
  3602: "Personal Care Aides",
  3603: "Nursing Assistants",
  3605: "Orderlies and Psychiatric Aides",
  3610: "Occupational Therapy Assistants And Aides",
  3620: "Physical Therapist Assistants And Aides",
  3630: "Massage Therapists",
  3640: "Dental Assistants",
  3645: "Medical Assistants",
  3646: "Medical Transcriptionists",
  3647: "Pharmacy Aides",
  3648: "Veterinary Assistants",
  3649: "Phlebotomists",
  3655: "Other Healthcare Support Workers",
  3700: "First-Line Supervisors Of Correctional Officers",
  3710: "First-Line Supervisors Of Police And Detectives",
  3720: "First-Line Supervisors Of Firefighting",
  3725: "Miscellaneous First-Line Supervisors, Protective Service",
  3740: "Firefighters",
  3750: "Fire Inspectors",
  3801: "Bailiffs",
  3802: "Correctional Officers and Jailers",
  3820: "Detectives And Criminal Investigators",
  3840: "Fish And Game Wardens And Parking Enforcement Officers",
  3870: "Police Officers",
  3900: "Animal Control Workers",
  3910: "Private Detectives And Investigators",
  3930: "Security Guards And Gambling Surveillance Officers",
  3940: "Crossing Guards And Flaggers",
  3945: "Transportation Security Screeners",
  3946: "School Bus Monitors",
  3960: "Other Protective Service Workers",
  4000: "Chefs And Head Cooks",
  4010: "First-Line Supervisors Of Food Preparation",
  4020: "Cooks",
  4030: "Food Preparation Workers",
  4040: "Bartenders",
  4055: "Fast Food And Counter Workers",
  4110: "Waiters And Waitresses",
  4120: "Food Servers, Nonrestaurant",
  4130: "Dining Room And Cafeteria Attendants",
  4140: "Dishwashers",
  4150: "Hosts And Hostesses, Restaurant",
  4160: "Food Preparation and Serving Related Workers",
  4200: "First-Line Supervisors Of Housekeeping",
  4210: "First-Line Supervisors Of Landscaping",
  4220: "Janitors And Building Cleaners",
  4230: "Maids And Housekeeping Cleaners",
  4240: "Pest Control Workers",
  4251: "Landscaping And Groundskeeping Workers",
  4252: "Tree Trimmers and Pruners",
  4255: "Other Grounds Maintenance Workers",
  4330: "Supervisors Of Personal Care And Service Workers",
  4340: "Animal Trainers",
  4350: "Animal Caretakers",
  4400: "Gambling Services Workers",
  4420: "Ushers, Lobby Attendants, And Ticket Takers",
  4435: "Other Entertainment Attendants",
  4461: "Embalmers, Crematory Operators And Funeral Attendants",
  4465: "Morticians, Undertakers, And Funeral Arrangers",
  4500: "Barbers",
  4510: "Hairdressers, Hairstylists, And Cosmetologists",
  4521: "Manicurists And Pedicurists",
  4522: "Skincare Specialists",
  4525: "Other Personal Appearance Workers",
  4530: "Baggage Porters, Bellhops, And Concierges",
  4540: "Tour And Travel Guides",
  4600: "Childcare Workers",
  4621: "Exercise Trainers And Group Fitness Instructors",
  4622: "Recreation Workers",
  4640: "Residential Advisors",
  4655: "Personal Care and Service Workers, All Other",
  4700: "First-Line Supervisors Of Retail Sales Workers",
  4710: "First-Line Supervisors Of Non-Retail Sales Workers",
  4720: "Cashiers",
  4740: "Counter And Rental Clerks",
  4750: "Parts Salespersons",
  4760: "Retail Salespersons",
  4800: "Advertising Sales Agents",
  4810: "Insurance Sales Agents",
  4820: "Securities, Commodities, And Financial Services Sales Agents",
  4830: "Travel Agents",
  4840: "Sales Representatives Of Services",
  4850: "Sales Representatives, Wholesale And Manufacturing",
  4900: "Models, Demonstrators, And Product Promoters",
  4920: "Real Estate Brokers And Sales Agents",
  4930: "Sales Engineers",
  4940: "Telemarketers",
  4950: "Door-To-Door Sales Workers",
  4965: "Sales And Related Workers, All Other",
  5000: "First-Line Supervisors Of Office Workers",
  5010: "Switchboard Operators",
  5020: "Telephone Operators",
  5040: "Communications Equipment Operators",
  5100: "Bill And Account Collectors",
  5110: "Billing And Posting Clerks",
  5120: "Bookkeeping, Accounting, And Auditing Clerks",
  5140: "Payroll And Timekeeping Clerks",
  5150: "Procurement Clerks",
  5160: "Tellers",
  5165: "Other Financial Clerks",
  5220: "Court, Municipal, And License Clerks",
  5230: "Credit Authorizers, Checkers, And Clerks",
  5240: "Customer Service Representatives",
  5250: "Eligibility Interviewers, Government Programs",
  5260: "File Clerks",
  5300: "Hotel, Motel, And Resort Desk Clerks",
  5310: "Interviewers, Except Eligibility And Loan",
  5320: "Library Assistants, Clerical",
  5330: "Loan Interviewers And Clerks",
  5340: "New Accounts Clerks",
  5350: "Correspondence Clerks And Order Clerks",
  5360: "Human Resources Assistants",
  5400: "Receptionists And Information Clerks",
  5410: "Reservation And Transportation Ticket Agents",
  5420: "Other Information And Records Clerks",
  5500: "Cargo And Freight Agents",
  5510: "Couriers And Messengers",
  5521: "Public Safety Telecommunicators",
  5522: "Dispatchers, Except Police, Fire, And Ambulance",
  5530: "Meter Readers, Utilities",
  5540: "Postal Service Clerks",
  5550: "Postal Service Mail Carriers",
  5560: "Postal Service Mail Sorters",
  5600: "Production, Planning, And Expediting Clerks",
  5610: "Shipping, Receiving, And Inventory Clerks",
  5630: "Weighers, Measurers, Checkers, And Samplers",
  5710: "Executive Secretaries And Executive Administrative Assistants",
  5720: "Legal Secretaries and Administrative Assistants",
  5730: "Medical Secretaries and Administrative Assistants",
  5740: "Secretaries And Administrative Assistants",
  5810: "Data Entry Keyers",
  5820: "Word Processors And Typists",
  5840: "Insurance Claims And Policy Processing Clerks",
  5850: "Mail Clerks And Mail Machine Operators",
  5860: "Office Clerks, General",
  5900: "Office Machine Operators",
  5910: "Proofreaders And Copy Markers",
  5920: "Statistical Assistants",
  5940: "Other Office And Administrative Support Workers",
  6005: "First-Line Supervisors Of Farming, Fishing, And Forestry",
  6010: "Agricultural Inspectors",
  6040: "Graders And Sorters, Agricultural Products",
  6050: "Other Agricultural Workers",
  6115: "Fishing And Hunting Workers",
  6120: "Forest And Conservation Workers",
  6130: "Logging Workers",
  6200: "First-Line Supervisors Of Construction Trades",
  6210: "Boilermakers",
  6220: "Brickmasons, Blockmasons, Stonemasons",
  6230: "Carpenters",
  6240: "Carpet, Floor, And Tile Installers",
  6250: "Cement Masons, Concrete Finishers",
  6260: "Construction Laborers",
  6305: "Construction Equipment Operators",
  6330: "Drywall Installers, Ceiling Tile Installers",
  6355: "Electricians",
  6360: "Glaziers",
  6400: "Insulation Workers",
  6410: "Painters and Paperhangers",
  6441: "Pipelayers",
  6442: "Plumbers, Pipefitters, And Steamfitters",
  6460: "Plasterers And Stucco Masons",
  6515: "Roofers",
  6520: "Sheet Metal Workers",
  6530: "Structural Iron And Steel Workers",
  6540: "Solar Photovoltaic Installers",
  6600: "Helpers, Construction Trades",
  6660: "Construction And Building Inspectors",
  6700: "Elevator And Escalator Installers And Repairers",
  6710: "Fence Erectors",
  6720: "Hazardous Materials Removal Workers",
  6730: "Highway Maintenance Workers",
  6740: "Rail-Track Laying And Maintenance Equipment Operators",
  6765: "Other Construction And Related Workers",
  6800: "Derrick, Rotary Drill, And Service Unit Operators",
  6825: "Surface Mining Machine Operators",
  6835: "Explosives Workers",
  6850: "Underground Mining Machine Operators",
  6950: "Other Extraction Workers",
  7000: "First-Line Supervisors Of Mechanics",
  7010: "Computer, Automated Teller, And Office Machine Repairers",
  7020: "Radio And Telecommunications Equipment Installers",
  7030: "Avionics Technicians",
  7040: "Electric Motor, Power Tool Repairers",
  7100: "Other Electrical And Electronic Equipment Mechanics",
  7120: "Audiovisual Equipment Installers And Repairers",
  7130: "Security And Fire Alarm Systems Installers",
  7140: "Aircraft Mechanics And Service Technicians",
  7150: "Automotive Body And Related Repairers",
  7160: "Automotive Glass Installers And Repairers",
  7200: "Automotive Service Technicians And Mechanics",
  7210: "Bus And Truck Mechanics And Diesel Engine Specialists",
  7220: "Heavy Vehicle And Mobile Equipment Service Technicians",
  7240: "Small Engine Mechanics",
  7260: "Miscellaneous Vehicle And Mobile Equipment Mechanics",
  7300: "Control And Valve Installers And Repairers",
  7315: "Heating, Air Conditioning, And Refrigeration Mechanics",
  7320: "Home Appliance Repairers",
  7330: "Industrial And Refractory Machinery Mechanics",
  7340: "Maintenance And Repair Workers, General",
  7350: "Maintenance Workers, Machinery",
  7360: "Millwrights",
  7410: "Electrical Power-Line Installers And Repairers",
  7420: "Telecommunications Line Installers And Repairers",
  7430: "Precision Instrument And Equipment Repairers",
  7510: "Coin, Vending, And Amusement Machine Servicers",
  7540: "Locksmiths And Safe Repairers",
  7560: "Riggers",
  7610: "Helpers--Installation, Maintenance, And Repair Workers",
  7640: "Other Installation, Maintenance, And Repair Workers",
  7700: "First-Line Supervisors Of Production Workers",
  7720: "Electrical, Electronics, And Electromechanical Assemblers",
  7730: "Engine And Other Machine Assemblers",
  7740: "Structural Metal Fabricators And Fitters",
  7750: "Other Assemblers And Fabricators",
  7800: "Bakers",
  7810: "Butchers And Other Meat, Poultry, And Fish Processing Workers",
  7830: "Food And Tobacco Roasting, Baking, And Drying Machine Operators",
  7840: "Food Batchmakers",
  7850: "Food Cooking Machine Operators And Tenders",
  7855: "Food Processing Workers, All Other",
  7905: "Computer Numerically Controlled Tool Operators",
  7925: "Forming Machine Setters, Operators, And Tenders",
  7950: "Cutting, Punching, And Press Machine Setters",
  8000: "Grinding, Lapping, Polishing, And Buffing Machine Tool Setters",
  8025: "Other Machine Tool Setters",
  8030: "Machinists",
  8040: "Metal Furnace Operators, Tenders, Pourers, And Casters",
  8100: "Model Makers, Patternmakers, And Molding Machine Setters",
  8130: "Tool And Die Makers",
  8140: "Welding, Soldering, And Brazing Workers",
  8225: "Other Metal Workers And Plastic Workers",
  8250: "Prepress Technicians And Workers",
  8255: "Printing Press Operators",
  8256: "Print Binding And Finishing Workers",
  8300: "Laundry And Dry-Cleaning Workers",
  8310: "Pressers, Textile, Garment, And Related Materials",
  8320: "Sewing Machine Operators",
  8335: "Shoe And Leather Workers",
  8350: "Tailors, Dressmakers, And Sewers",
  8365: "Textile Machine Setters, Operators, And Tenders",
  8450: "Upholsterers",
  8465: "Other Textile, Apparel, And Furnishings Workers",
  8500: "Cabinetmakers And Bench Carpenters",
  8510: "Furniture Finishers",
  8530: "Sawing Machine Setters, Operators, And Tenders",
  8540: "Woodworking Machine Setters, Operators, And Tenders",
  8555: "Other Woodworkers",
  8600: "Power Plant Operators, Distributors, And Dispatchers",
  8610: "Stationary Engineers And Boiler Operators",
  8620: "Water And Wastewater Treatment Plant Operators",
  8630: "Miscellaneous Plant And System Operators",
  8640: "Chemical Processing Machine Setters",
  8650: "Crushing, Grinding, Polishing, Mixing, And Blending Workers",
  8710: "Cutting Workers",
  8720: "Extruding, Forming, Pressing, And Compacting Machine Setters",
  8730: "Furnace, Kiln, Oven, Drier, And Kettle Operators",
  8740: "Inspectors, Testers, Sorters, Samplers, And Weighers",
  8750: "Jewelers And Precious Stone And Metal Workers",
  8760: "Dental And Ophthalmic Laboratory Technicians",
  8800: "Packaging And Filling Machine Operators And Tenders",
  8810: "Painting Workers",
  8830: "Photographic Process Workers",
  8850: "Adhesive Bonding Machine Operators And Tenders",
  8910: "Etchers And Engravers",
  8920: "Molders, Shapers, And Casters",
  8930: "Paper Goods Machine Setters, Operators, And Tenders",
  8940: "Tire Builders",
  8950: "Helpers--Production Workers",
  8990: "Miscellaneous Production Workers",
  9005: "Supervisors Of Transportation",
  9030: "Aircraft Pilots And Flight Engineers",
  9040: "Air Traffic Controllers",
  9050: "Flight Attendants",
  9110: "Ambulance Drivers And Attendants",
  9121: "Bus Drivers, School",
  9122: "Bus Drivers, Transit And Intercity",
  9130: "Driver/Sales Workers And Truck Drivers",
  9141: "Shuttle Drivers And Chauffeurs",
  9142: "Taxi Drivers",
  9150: "Motor Vehicle Operators, All Other",
  9210: "Locomotive Engineers And Operators",
  9240: "Railroad Conductors And Yardmasters",
  9265: "Other Rail Transportation Workers",
  9300: "Sailors And Marine Oilers, And Ship Engineers",
  9310: "Ship And Boat Captains And Operators",
  9350: "Parking Attendants",
  9365: "Transportation Service Attendants",
  9410: "Transportation Inspectors",
  9415: "Passenger Attendants",
  9430: "Other Transportation Workers",
  9510: "Crane And Tower Operators",
  9570: "Conveyor, Dredge, And Hoist and Winch Operators",
  9600: "Industrial Truck And Tractor Operators",
  9610: "Cleaners Of Vehicles And Equipment",
  9620: "Laborers And Freight, Stock, And Material Movers",
  9630: "Machine Feeders And Offbearers",
  9640: "Packers And Packagers, Hand",
  9645: "Stockers And Order Fillers",
  9650: "Pumping Station Operators",
  9720: "Refuse And Recyclable Material Collectors",
  9760: "Other Material Moving Workers",
  9800: "Military Officer Special And Tactical Operations Leaders",
  9810: "First-Line Enlisted Military Supervisors",
  9825: "Military Enlisted Tactical Operations",
  9830: "Military, Rank Not Specified",
  9920: "Unemployed",
};
